authors = ["<oss@fastly.com>"]
description = ""
language = "rust"
manifest_version = 2
name = "Geo-IP API at the edge"

[local_server.backends.origin_0]
      url = "https://http-me.glitch.me"

[setup.backends.origin_0]
address = "http-me.glitch.me"
port = 443
